/**
 * @author Emmet Stanevich
 * Stores an ordered collection of objects, which can have values added to and removed from it
 * Created using the textbook as reference
 * Cleaned up using suggestions auto-generated by the IDE
 */
public class OrderedCollection <AnyType extends Comparable<? super AnyType>> {
	public OrderedCollection(){
	
	}
	
	/**
	 * Simply returns a list of values in the collection, separated by commas
	 * Cleaned up using Intellij's inspections suggestions
	 * @return the list of entries, separated by commas
	 */
	public String toString(){
		StringBuilder output = null;
		if(!isEmpty()){
			output = new StringBuilder((String) memory[0]);
			if(memory.length>1){
				
				for(int i=1; i<memory.length;i++){
					output.append(", ").append(memory[i]);
				}
			}
		}
		assert output != null;
		return output.toString();
	}
	/**
	 * Returns the positional index of a specified object
	 * @param x the object for the function to look for
	 */
	private int search(Comparable<? super AnyType> x){
		if(!isEmpty()){
			int pos=-1;
			for(int i=0;i<memory.length;i++){
				if(memory[i]==x)return i;
			}
			return -1;
		}
		else return -1;
	}
	
	/**
	 * @return true if the array is empty, false otherwise
	 */
	public boolean isEmpty(){
		return memory == null;
	}
	/**
	 * Sets the array to null
	 */
	public void makeEmpty(){
		memory=null;
	}
	/**
	 * Adds a new entry to the end of the array
	 * @param newEntry the entry to be added
	 */
	public void insert(Comparable<? super AnyType> newEntry){
		if(isEmpty()){
			memory=new Comparable[1];
			memory[0]= newEntry;
		}
		else {
			Comparable [] tempMem=new Comparable[memory.length+1];
			for(int i=0;i<memory.length;i++)tempMem[i]=memory[i];
			tempMem[memory.length]=newEntry;
			memory=tempMem;
		}
		
	}
	
	/**
	 * Removes a specified entry, then runs the clean() method
	 * @param target the entry to be removed
	 * @return true if the entry is successfully found and removed, false otherwise
	 */
	public boolean remove(AnyType target){
		for (int i=0;i<memory.length;i++){
			if(memory[i].compareTo(target)==0){
				memory[i]=null;
				clean();
				return true;
			}
		}return false;
	}
	
	/**
	 * Searches the array for any null entries, then snips them out
	 */
	private void clean(){
		int size=0;
		for (Comparable comparable : memory) {
			if (comparable != null) size++;
		}
		Comparable [] tempMem=new Comparable[size];
		int memIndex=0;
		for(int tempMemIndex=0; tempMemIndex<size;tempMemIndex++){
			if(memory[memIndex]!=null) tempMem[tempMemIndex]=memory[memIndex];
			else tempMemIndex--;
			memIndex++;
		}
		memory=tempMem;
	}
	
	/**
	 * @return the size of the array
	 */
	private int memSize(){
		return memory.length;
	}
	private Comparable [] memory = null;
	
	/**
	 * Searches the array, looking for the highest value
	 * @param <AnyType> the type of value to be returned
	 * @return the largest value in the array
	 */
	public <AnyType extends Comparable<? super  AnyType>>
	AnyType findMax(){
		if(!isEmpty()){
			int maxIndex=0;
			for(int i=0;i<memory.length;i++){
				if(memory[i].compareTo(memory[maxIndex])>0)maxIndex=i;
			}
			return (AnyType) memory[maxIndex];
		}
		else return null;
	}
	
	/**
	 * Searches the array, looking for the lowest value
	 * @param <AnyType> the type of value to be returned
	 * @return the smallest value in the array
	 */
	public <AnyType extends Comparable<? super AnyType>>
	AnyType findMin(){
		if(!isEmpty()){
			int minIndex=0;
			for(int i=0;i<memory.length;i++){
				if(memory[i].compareTo(memory[minIndex])<0)minIndex=i;
			}
			return (AnyType) memory[minIndex];
		}
		else return null;
	}
	public static void main(String[] args){
		OrderedCollection<Integer> x = new OrderedCollection<>();
		System.out.println(x.isEmpty());
		x.insert(10);
		x.insert(12);
		x.insert(15);
		System.out.println(x.isEmpty());
		System.out.println(x.search(10));
		System.out.println(x.search(12));
		System.out.println(x.memSize());
		System.out.println(x.remove(12));
		System.out.println(x.search(10));
		System.out.println(x.search(15));
		System.out.println(x.memSize());
		System.out.println((String) x.findMax());
		System.out.println((String) x.findMin());
		x.makeEmpty();
		System.out.println(x.isEmpty());
	}
}
